export const ORDER_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  EXPIRED: 'EXPIRED',
  CANCELED: 'CANCELED',
};

export const DELIVERY_STATUS = {
  PENDING: 'PENDING',
  ORDER_PROCESSING: 'ORDER_PROCESSING',
  SHIPPED: 'SHIPPED',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED',
};
